package com.latch.data

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.latch.core.model.RoutingMode
import java.io.IOException
import java.security.GeneralSecurityException
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM under a key held in the Android Keystore, where the key material is not
 * readable by this process at all — only usable through it.
 *
 * NFR-501 is why this is written out rather than pulled in. `androidx.security:security-crypto`
 * does the same job, but it is a dependency that would need justifying, and Google deprecated
 * it in favour of using these platform APIs directly. The whole of it is below.
 *
 * The alias is deliberately generic: NFR-203's secret store (OAuth tokens, and the FR-1004
 * webhook URL) needs exactly this and should reuse it rather than mint a second scheme.
 */
internal class KeystoreCipher(private val alias: String) {

    /** Throws rather than degrades. A caller that cannot encrypt must not write plaintext. */
    fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        // The IV is generated by the cipher, never reused, and carried with the record.
        return Base64.getEncoder().encodeToString(cipher.iv + ciphertext)
    }

    /**
     * Null for anything that cannot be read back: a truncated record, a failed GCM tag, or
     * a key the Keystore no longer holds. The last of those is real — the key does not
     * survive a restore onto another device — and the honest reading of all three is the
     * same, that this entry is gone.
     */
    fun decrypt(encoded: String): String? = try {
        val bytes = Base64.getDecoder().decode(encoded)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, bytes, 0, IV_BYTES))
        String(cipher.doFinal(bytes, IV_BYTES, bytes.size - IV_BYTES), Charsets.UTF_8)
    } catch (unreadable: GeneralSecurityException) {
        null
    } catch (unreadable: IOException) {
        null
    } catch (unreadable: IllegalArgumentException) {
        null
    }

    private fun key(): SecretKey {
        val keystore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keystore.getKey(alias, null) as? SecretKey)?.let { return it }

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER).apply {
            init(
                KeyGenParameterSpec.Builder(
                    alias,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(KEY_BITS)
                    .build()
            )
        }.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_BITS = 256
        const val TAG_BITS = 128
        const val IV_BYTES = 12
    }
}

/**
 * [AccountDefaultsStore] over app-private preferences, each record encrypted by
 * [KeystoreCipher]. This is what stops setup running on every launch: until now defaults
 * lived only as long as the process.
 *
 * Not Room. The seven §7.1 entities may justify it later, but four strings and an enum per
 * account do not, and Room is deferred on build-configuration grounds in docs/DEPENDENCIES.md.
 *
 * **These `suspend` functions block on the thread that calls them.** `:data` carries no
 * coroutines dependency (NFR-501), so there is no `Dispatchers.IO` to switch to here and
 * the dispatcher is the caller's to choose. Both current callers are already off the main
 * thread. If `:data` ever gains coroutines, this is the first thing to fix.
 */
class EncryptedAccountDefaultsStore(context: Context) : AccountDefaultsStore {

    private val prefs: SharedPreferences =
        context.applicationContext.getSharedPreferences(PREFS_FILE, Context.MODE_PRIVATE)

    private val cipher = KeystoreCipher(KEY_ALIAS)

    override suspend fun defaultsFor(accountId: String): AccountDefaults? = read(keyFor(accountId))

    override suspend fun allAccounts(): List<AccountDefaults> =
        prefs.all.keys.filter { it.startsWith(ACCOUNT_PREFIX) }.sorted().mapNotNull(::read)

    /**
     * `commit`, not `apply`. SetupCoordinator turns a failure here into
     * `DEFAULTS_NOT_SAVED`, and `apply` cannot report one — it would return having written
     * nothing, and setup would declare itself complete over a calendar nothing points at.
     */
    override suspend fun save(defaults: AccountDefaults) {
        val written = prefs.edit()
            .putString(keyFor(defaults.accountId), cipher.encrypt(encodeDefaults(defaults)))
            .commit()
        check(written) { "Account defaults for ${defaults.accountId} were not written to disk." }
    }

    override suspend fun remove(accountId: String) {
        prefs.edit().remove(keyFor(accountId)).commit()
    }

    private fun read(key: String): AccountDefaults? {
        val stored = prefs.getString(key, null) ?: return null
        val defaults = cipher.decrypt(stored)?.let(::decodeDefaults)
        if (defaults == null) {
            // Unreadable now means unreadable forever, and an entry that can never be
            // decrypted but still exists would leave the account permanently half-present.
            // Dropping it sends the user back through setup (FR-101), which is the only
            // recovery that does not invent a configuration.
            prefs.edit().remove(key).apply()
        }
        return defaults
    }

    /**
     * The account id appears in the preference key in the clear; everything with content —
     * the email, the destinations — is inside the encrypted record. A Google account id is
     * an opaque number, and keeping it visible is what lets one account be read or removed
     * without decrypting the rest.
     */
    private fun keyFor(accountId: String) = ACCOUNT_PREFIX + accountId

    private companion object {
        const val PREFS_FILE = "account_defaults"
        const val KEY_ALIAS = "latch.prefs.v1"
        const val ACCOUNT_PREFIX = "account."
    }
}

/**
 * Field-separated rather than JSON, because JSON here would mean either a serialization
 * dependency or hand-rolled escaping. U+001F is the ASCII unit separator and cannot occur
 * in an account id, an email address or a Google resource id.
 *
 * The version leads, so that adding a field later is detected rather than mis-parsed: an
 * old record decodes to null and setup runs once more.
 */
internal fun encodeDefaults(defaults: AccountDefaults): String = listOf(
    RECORD_VERSION,
    defaults.accountId,
    defaults.email,
    defaults.routingMode.name,
    defaults.destinationCalendarId,
    defaults.taskListId,
).joinToString(SEPARATOR)

internal fun decodeDefaults(record: String): AccountDefaults? {
    val fields = record.split(SEPARATOR)
    if (fields.size != FIELD_COUNT || fields[0] != RECORD_VERSION) return null
    // Not valueOf: a mode written by a later version must decode to null, not throw.
    val mode = RoutingMode.entries.firstOrNull { it.name == fields[3] } ?: return null
    return AccountDefaults(
        accountId = fields[1],
        email = fields[2],
        routingMode = mode,
        destinationCalendarId = fields[4],
        taskListId = fields[5],
    )
}

private val SEPARATOR = Char(0x1F).toString()
private const val RECORD_VERSION = "1"
private const val FIELD_COUNT = 6
